# Advanced NumPy

In [3]:
from __future__ import division
from numpy.random import randn
from pandas import Series
import numpy as np
np.set_printoptions(precision=4)
import sys

## ndarray object internals

### NumPy dtype hierarchy

In [30]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)

True

In [32]:
np.issubdtype(ints.dtype, np.integer)

True

In [33]:
np.issubdtype(floats.dtype, np.floating)

True

In [11]:
type(ints)

numpy.ndarray

In [20]:
floats.shape


(10,)

In [23]:
test = np.ones((3, 4, 5), dtype=np.float64)

In [29]:
test.strides


(160, 40, 8)

In [35]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## Advanced array manipulation

### Reshaping arrays

In [39]:
arr = np.arange(8)
arr
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [42]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [45]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [51]:
other_arr = np.ones((3, 5))
other_arr.shape

tuple

In [50]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
arr = np.arange(15).reshape((5, 3))
arr
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr.flatten()

### C vs. Fortran order

In [ ]:
arr = np.arange(12).reshape((3, 4))
arr
arr.ravel()
arr.ravel('F')

### Concatenating and splitting arrays

In [65]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [66]:
np.vstack((arr1, arr2))
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [67]:
from numpy.random import randn
arr = randn(5, 2)
arr



array([[-0.1806,  0.6724],
       [-1.9509,  0.7302],
       [-0.5983, -1.9478],
       [ 0.9625, -0.819 ],
       [-1.0657,  0.7304]])

In [68]:
first, second, third = np.split(arr, [1, 3])

In [62]:
first

array([[-0.5771,  0.7309]])

In [63]:
second

array([[ 0.3579, -0.698 ],
       [-0.6419, -1.3989]])

In [64]:
third

array([[-0.9348,  0.4426],
       [-2.2799, -1.8038]])

#### Stacking helpers: 

In [75]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [76]:
arr1 = arr.reshape((3, 2))
arr2 = randn(3, 2)

In [77]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [78]:
arr2

array([[-0.7454,  2.3819],
       [ 0.3333,  0.2232],
       [-0.7216, -1.0082]])

In [79]:
np.r_[arr1, arr2]


array([[ 0.    ,  1.    ],
       [ 2.    ,  3.    ],
       [ 4.    ,  5.    ],
       [-0.7454,  2.3819],
       [ 0.3333,  0.2232],
       [-0.7216, -1.0082]])

In [81]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [-0.7454,  2.3819,  3.    ],
       [ 0.3333,  0.2232,  4.    ],
       [-0.7216, -1.0082,  5.    ]])

In [83]:
np.c_[1:6, -10:-5]


array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [84]:
np.r_[1:6,-10:-5]

array([  1,   2,   3,   4,   5, -10,  -9,  -8,  -7,  -6])

### Repeating elements: tile and repeat

In [85]:
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [86]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [96]:
arr = randn(2, 2)
arr
arr.repeat(2, axis=0)

array([[-0.1162, -0.9619],
       [-0.1162, -0.9619],
       [ 0.428 ,  1.6569],
       [ 0.428 ,  1.6569]])

In [97]:
arr.repeat(2)

array([-0.1162, -0.1162, -0.9619, -0.9619,  0.428 ,  0.428 ,  1.6569,
        1.6569])

In [98]:
arr.repeat([2, 3], axis=0)


array([[-0.1162, -0.9619],
       [-0.1162, -0.9619],
       [ 0.428 ,  1.6569],
       [ 0.428 ,  1.6569],
       [ 0.428 ,  1.6569]])

In [94]:
arr.repeat([2, 3], axis=1)

array([[ 0.8701,  0.8701,  0.8029,  0.8029,  0.8029],
       [-1.7083, -1.7083, -1.5796, -1.5796, -1.5796]])

In [105]:
arr
np.tile(arr, 2)

array([[-0.1162, -0.9619, -0.1162, -0.9619],
       [ 0.428 ,  1.6569,  0.428 ,  1.6569]])

In [111]:
arr
np.tile(arr, (2, 1))

array([[-0.1162, -0.9619],
       [ 0.428 ,  1.6569],
       [-0.1162, -0.9619],
       [ 0.428 ,  1.6569]])

In [112]:
np.tile(arr, (3, 2))

array([[-0.1162, -0.9619, -0.1162, -0.9619],
       [ 0.428 ,  1.6569,  0.428 ,  1.6569],
       [-0.1162, -0.9619, -0.1162, -0.9619],
       [ 0.428 ,  1.6569,  0.428 ,  1.6569],
       [-0.1162, -0.9619, -0.1162, -0.9619],
       [ 0.428 ,  1.6569,  0.428 ,  1.6569]])

### Fancy indexing equivalents: take and put

In [138]:
arr = np.arange(10) * 100
arr


array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [139]:
inds = [7, 1, 2, 6]
arr[inds]


array([700, 100, 200, 600])

In [140]:
arr.take(inds)



array([700, 100, 200, 600])

In [141]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [142]:
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [135]:
inds = [2, 0, 2, 1]
arr = randn(2, 4)
arr


array([[ 0.265 ,  1.6962, -0.4045, -0.4237],
       [ 0.2907,  0.7715,  0.9245,  0.5721]])

In [143]:
arr.take(inds, axis=1)

ValueError: axis(=1) out of bounds

## Broadcasting

In [146]:
arr = np.arange(5)
arr
arr * 4

array([ 0,  4,  8, 12, 16])

In [147]:
arr = randn(4, 3)
arr.mean(0)
demeaned = arr - arr.mean(0)
demeaned
demeaned.mean(0)

array([  0.0000e+00,   2.7756e-17,   2.7756e-17])

In [149]:
arr

array([[ 1.4355, -0.7298,  0.7692],
       [ 1.8044,  1.1344,  0.3688],
       [ 0.4945, -1.3916, -0.8287],
       [-0.354 ,  0.5522, -0.3953]])

In [151]:
row_means = arr.mean(1)
row_means

array([ 0.4917,  1.1025, -0.5753, -0.0657])

In [156]:
row_means.reshape((4, 1))
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([  3.7007e-17,   0.0000e+00,   0.0000e+00,   0.0000e+00])

### Broadcasting over other axes

In [157]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [159]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.9439, -1.2215,  0.2776],
       [ 0.7019,  0.0319, -0.7337],
       [ 1.0698, -0.8163, -0.2534],
       [-0.2883,  0.6179, -0.3296]])

In [160]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

In [162]:
arr_1d = np.random.normal(size=3)
arr_1d

array([ 1.4419, -1.8365,  1.271 ])

In [164]:
arr_1d[:, np.newaxis]


array([[ 1.4419],
       [-1.8365],
       [ 1.271 ]])

In [165]:
arr_1d[np.newaxis, :]

array([[ 1.4419, -1.8365,  1.271 ]])

In [166]:
arr = randn(3, 4, 5)
depth_means = arr.mean(2)
depth_means
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

array([[  2.2204e-17,  -4.4409e-17,   0.0000e+00,  -2.2204e-17],
       [  0.0000e+00,  -8.8818e-17,   3.3307e-17,   0.0000e+00],
       [ -2.2204e-17,   2.2204e-17,  -8.8818e-17,   1.1102e-17]])

In [192]:
[slice(None)] * arr.ndim

[slice(None, None, None), slice(None, None, None), slice(None, None, None)]

In [194]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalized things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

### Setting array values by broadcasting

In [198]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [199]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [201]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [202]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

## Advanced ufunc usage

### Ufunc instance methods

In [206]:
arr = np.arange(10)
np.add.reduce(arr)


45

In [208]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
np.add.reduce(arr)

45

In [211]:
arr.sum()

45

In [214]:
np.random.seed(12346)

In [220]:
arr = randn(5, 5)
arr

array([[  5.2242e-01,   1.0642e-01,   1.0271e-01,  -1.0823e-01,
          5.4860e-02],
       [  1.9637e-01,  -1.9387e-01,  -1.4566e+00,   8.5745e-01,
         -7.4158e-01],
       [ -7.8036e-01,  -1.0642e-01,   5.9371e-01,  -1.2835e+00,
          4.7796e-01],
       [  1.2924e+00,   1.5165e-01,  -1.4663e+00,  -1.4334e+00,
         -9.7753e-02],
       [  1.2351e+00,   1.3551e-01,  -7.0550e-04,   2.5360e-01,
         -1.8325e-01]])

In [222]:
arr[::2]

array([[  5.2242e-01,   1.0642e-01,   1.0271e-01,  -1.0823e-01,
          5.4860e-02],
       [ -7.8036e-01,  -1.0642e-01,   5.9371e-01,  -1.2835e+00,
          4.7796e-01],
       [  1.2351e+00,   1.3551e-01,  -7.0550e-04,   2.5360e-01,
         -1.8325e-01]])

In [225]:
arr[::2].sort(1) # sort a few rows
arr

array([[ -1.0823e-01,   5.4860e-02,   1.0271e-01,   1.0642e-01,
          5.2242e-01],
       [  1.9637e-01,  -1.9387e-01,  -1.4566e+00,   8.5745e-01,
         -7.4158e-01],
       [ -1.2835e+00,  -7.8036e-01,  -1.0642e-01,   4.7796e-01,
          5.9371e-01],
       [  1.2924e+00,   1.5165e-01,  -1.4663e+00,  -1.4334e+00,
         -9.7753e-02],
       [ -1.8325e-01,  -7.0550e-04,   1.3551e-01,   2.5360e-01,
          1.2351e+00]])

In [231]:
arr[:, :-1]

array([[ -1.0823e-01,   5.4860e-02,   1.0271e-01,   1.0642e-01],
       [  1.9637e-01,  -1.9387e-01,  -1.4566e+00,   8.5745e-01],
       [ -1.2835e+00,  -7.8036e-01,  -1.0642e-01,   4.7796e-01],
       [  1.2924e+00,   1.5165e-01,  -1.4663e+00,  -1.4334e+00],
       [ -1.8325e-01,  -7.0550e-04,   1.3551e-01,   2.5360e-01]])

In [232]:
arr[:, 1:]

array([[  5.4860e-02,   1.0271e-01,   1.0642e-01,   5.2242e-01],
       [ -1.9387e-01,  -1.4566e+00,   8.5745e-01,  -7.4158e-01],
       [ -7.8036e-01,  -1.0642e-01,   4.7796e-01,   5.9371e-01],
       [  1.5165e-01,  -1.4663e+00,  -1.4334e+00,  -9.7753e-02],
       [ -7.0550e-04,   1.3551e-01,   2.5360e-01,   1.2351e+00]])

In [233]:
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [237]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)
np.all(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [240]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [241]:
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [244]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [245]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [249]:
result = np.subtract.outer(randn(3, 4), randn(5))
result.shape

(3, 4, 5)

In [250]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [252]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr


array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [253]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

### Custom ufuncs

In [256]:
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [259]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
result = add_them(np.arange(8), np.arange(8))

In [260]:
type(result)

numpy.ndarray

In [262]:
arr = randn(10000)
arr

array([ 0.7439,  0.8688, -0.4286, ..., -1.3688, -0.9731,  0.2897])

In [264]:
%timeit add_them(arr, arr)


100 loops, best of 3: 2.31 ms per loop


In [265]:
%timeit np.add(arr, arr)

The slowest run took 25.86 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 6.14 µs per loop


## Structured and record arrays

In [267]:
dtype = [('x', np.float64), ('y', np.int32)]
dtype

[('x', numpy.float64), ('y', numpy.int32)]

In [270]:
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5, 6), (3.141592653589793, -2)], 
      dtype=[('x', '<f8'), ('y', '<i4')])

In [271]:
sarr[0]
sarr[0]['y']

6

In [278]:
sarr['x']

array([ 1.5   ,  3.1416])

### Nested dtypes and multidimensional fields

In [279]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)], 
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [280]:
arr[0]['x']

array([0, 0, 0])

In [281]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [283]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']


array([(1.0, 2.0), (3.0, 4.0)], 
      dtype=[('a', '<f8'), ('b', '<f4')])

In [285]:
data['y']


array([5, 6], dtype=int32)

In [286]:
data['x']['a']

array([ 1.,  3.])

### Why use structured arrays?

### Structured array manipulations: numpy.lib.recfunctions

## More about sorting

In [287]:
arr = randn(6)
arr.sort()
arr

array([-1.5799, -1.3484, -1.1343, -0.7371, -0.5734, -0.4247])

In [288]:
arr = randn(3, 5)
arr
arr[:, 0].sort()  # Sort first column values in-place
arr

array([[-0.8286, -1.1869,  1.9229,  0.6173, -0.4207],
       [-0.5543, -1.1959, -0.2837, -1.1584,  0.8378],
       [ 0.7781, -0.9529,  1.5012,  1.1616, -1.5151]])

In [292]:
arr = randn(5)
arr

array([ 0.3169, -0.2195, -0.1256, -0.4012,  0.4898])

In [293]:
np.sort(arr)
arr

array([ 0.3169, -0.2195, -0.1256, -0.4012,  0.4898])

In [296]:
arr = randn(3, 5)
arr

array([[ 0.6323, -0.1536, -0.0917, -1.1694, -0.453 ],
       [ 1.0465,  1.3795,  0.4973,  0.0457,  0.8922],
       [ 0.4556,  0.6815, -0.2598, -1.0817, -0.6778]])

In [297]:
arr.sort(axis=1)
arr

array([[-1.1694, -0.453 , -0.1536, -0.0917,  0.6323],
       [ 0.0457,  0.4973,  0.8922,  1.0465,  1.3795],
       [-1.0817, -0.6778, -0.2598,  0.4556,  0.6815]])

In [298]:
arr[:, ::-1]

array([[ 0.6323, -0.0917, -0.1536, -0.453 , -1.1694],
       [ 1.3795,  1.0465,  0.8922,  0.4973,  0.0457],
       [ 0.6815,  0.4556, -0.2598, -0.6778, -1.0817]])

### Indirect sorts: argsort and lexsort

In [300]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer


array([1, 2, 4, 3, 0])

In [301]:
values[indexer]

array([0, 1, 2, 3, 5])

In [326]:
arr = randn(3, 5)
arr[0] = values
arr


array([[ 5.    ,  0.    ,  1.    ,  3.    ,  2.    ],
       [-0.6253, -1.3372,  0.0795,  0.1051,  0.0927],
       [-0.3194,  1.6293,  1.1474, -1.1369,  0.7866]])

In [328]:
arr[:, arr[0].argsort()]

array([[ 0.    ,  1.    ,  2.    ,  3.    ,  5.    ],
       [-1.3372,  0.0795,  0.0927,  0.1051, -0.6253],
       [ 1.6293,  1.1474,  0.7866, -1.1369, -0.3194]])

In [353]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))

In [342]:
np.lexsort((first_name,last_name))

array([1, 2, 3, 0, 4])

In [335]:
first_name, last_name

(array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'], 
       dtype='|S7'), array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'], 
       dtype='|S7'))

In [347]:
last_name[sorter]

array(['Arnold', 'Arnold', 'Jones', 'Jones', 'Walters'], 
      dtype='|S7')

In [349]:
first_name[sorter]

array(['Jane', 'Steve', 'Bill', 'Bob', 'Barbara'], 
      dtype='|S7')

In [355]:
sorter = np.lexsort((first_name, last_name))
zip(last_name[sorter], first_name[sorter])

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

### Alternate sort algorithms

In [361]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'], 
      dtype='|S8')

### numpy.searchsorted: Finding elements in a sorted array

In [362]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

3

In [363]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

In [367]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])

array([0, 3])

In [368]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

In [369]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

array([ 6551.,   734.,   894.,  6695.,  5383.,  6559.,  4113.,  2970.,
        9692.,   533.,  3351.,  3401.,  6333.,  3412.,  6776.,  9285.,
        7975.,  4652.,  1350.,  2588.,  6867.,  1403.,   388.,   404.,
        9236.,  7008.,  4245.,  5376.,   118.,  3744.,  3332.,  8103.,
        9045.,  1947.,  4197.,  5373.,   750.,  8114.,  9870.,  5066.,
        8834.,  8368.,  2812.,  9485.,  8426.,  8956.,  7813.,  1275.,
        2988.,  6967.])

In [370]:
labels = bins.searchsorted(data)
labels

array([4, 2, 2, 4, 4, 4, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 4, 3, 3, 3, 4, 3, 2,
       2, 4, 4, 3, 4, 2, 3, 3, 4, 4, 3, 3, 4, 2, 4, 4, 4, 4, 4, 3, 4, 4, 4,
       4, 3, 3, 4])

In [371]:
Series(data).groupby(labels).mean()

2     545.857143
3    3045.882353
4    7621.384615
dtype: float64

In [372]:
np.digitize(data, bins)

array([4, 2, 2, 4, 4, 4, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 4, 3, 3, 3, 4, 3, 2,
       2, 4, 4, 3, 4, 2, 3, 3, 4, 4, 3, 3, 4, 2, 4, 4, 4, 4, 4, 3, 4, 4, 4,
       4, 3, 3, 4])

## NumPy matrix class

In [387]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])


In [388]:
X[:, 0]  # one-dimensional


array([ 8.8277,  3.8222, -1.1428,  2.0441])

In [376]:
y = X[:, :1]  # two-dimensional by slicing
y

array([[ 8.8277],
       [ 3.8222],
       [-1.1428],
       [ 2.0441]])

In [386]:
X[:,1:]

array([[ 3.8222, -1.1428,  2.0441],
       [ 6.7527,  0.8391,  2.0829],
       [ 0.8391,  5.0169,  0.7957],
       [ 2.0829,  0.7957,  6.241 ]])

In [389]:
np.dot(y.T, np.dot(X, y))

array([[ 1195.468]])

In [391]:
Xm = np.matrix(X)
ym = Xm[:, 0]

In [392]:
Xm


matrix([[ 8.8277,  3.8222, -1.1428,  2.0441],
        [ 3.8222,  6.7527,  0.8391,  2.0829],
        [-1.1428,  0.8391,  5.0169,  0.7957],
        [ 2.0441,  2.0829,  0.7957,  6.241 ]])

In [393]:
ym

matrix([[ 8.8277],
        [ 3.8222],
        [-1.1428],
        [ 2.0441]])

In [394]:
ym.T * Xm * ym

matrix([[ 1195.468]])

In [395]:
Xm.I * X

matrix([[  1.0000e+00,  -2.0817e-17,  -5.5511e-17,   5.5511e-17],
        [  1.5266e-16,   1.0000e+00,   5.5511e-17,   5.5511e-17],
        [  1.1102e-16,   2.7756e-17,   1.0000e+00,   1.3878e-17],
        [ -5.5511e-17,   0.0000e+00,   3.4694e-18,   1.0000e+00]])

## Advanced array input and output

### Memory-mapped files

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))
mmap

In [ ]:
section = mmap[:5]

In [ ]:
section[:] = np.random.randn(5, 10000)
mmap.flush()
mmap
del mmap

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

In [ ]:
%xdel mmap
!rm mymmap

### HDF5 and other array storage options

## Performance tips

### The importance of contiguous memory

In [ ]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')
arr_c.flags
arr_f.flags
arr_f.flags.f_contiguous

In [ ]:
%timeit arr_c.sum(1)
%timeit arr_f.sum(1)

In [ ]:
arr_f.copy('C').flags

In [ ]:
arr_c[:50].flags.contiguous
arr_c[:, :50].flags

In [ ]:
%xdel arr_c
%xdel arr_f
%cd ..

## Other speed options: Cython, f2py, C

```cython
from numpy cimport ndarray, float64_t

def sum_elements(ndarray[float64_t] arr):
    cdef Py_ssize_t i, n = len(arr)
    cdef float64_t result = 0

    for i in range(n):
        result += arr[i]

    return result
```